# Site settings
title: Mike's Projects
author:
  name: Mike Hankinson
  email: mmhankinson@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: daattali/beautiful-jekyll

